apiVersion: v1
kind: ConfigMap
metadata:
  name: yarn-config
data:
  yarn-site.xml: |
    <configuration>
        <property>
                <name>yarn.acl.enable</name>
                <value>0</value>
        </property>

        <property>
                <name>yarn.resourcemanager.hostname</name>
                <value>{{ .Values.masterIP }}</value>
        </property>

        <property>
                <name>yarn.nodemanager.aux-services</name>
                <value>mapreduce_shuffle</value>
        </property>
    </configuration>